# Generated by Django 3.2 on 2022-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, choices=[('Company A', 'Company A'), ('Company B', 'Company B'), ('Company C', 'Company C'), ('Company D', 'Company D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, choices=[('Company 1', 'Company 1'), ('Company 2', 'Company 2'), ('Company 3', 'Company 3'), ('Company 4', 'Company 4')], max_length=100, null=True),
        ),
    ]
